/*
 * file: osmonweb_POSIX_objs.c
 * Do not edit here!
 */
 #include "osmonweb_POSIX_objs.h"
   const char osmonweb_POSIX_objs_title[] =
      "\n"
      "<head>\n"
      "<!-- start of document title here -->\n"
      "   <title>RTEMS POSIX API Objects on <!--%printstr"
      " %s|4 --></title>\n"
      "<!-- end of document title -->\n"
      "</head>\n"
      "<body>\n"
   ;

   const char osmonweb_POSIX_objs_header[] =
      "\n"
      "<table border=\"0\" cellspacing=\"0\" cellpadding="
      "\"5\" width=\"100%\">\n"
      "   <tr><td><div align=\"center\">\n"
      "      <h2>RTEMS POSIX API Objects On Target <b><fo"
      "nt color=\"#4040ff\"><!--%printstr %s|4 --></font>"
      "</b></h2>\n"
      "   </div></td></tr>\n"
      "   <tr><td>\n"
      "   <div align=\"center\">\n"
      "   <!-- start of API selection bar -->\n"
      "   <table border=\"0\" cellspacing=\"0\" width=\"1"
      "00%\">\n"
      "      <tr valign=\"center\">\n"
      "      <td width=\"20\">&nbsp;</td>\n"
      "      <td bgcolor=\"#E0E0E0\" align=\"center\" wid"
      "th=\"200\">\n"
      "         <a href=\"/goforms/osmonweb?api=RTEID\" n"
      "ame=\"RTEID objects\">\n"
      "         <font color=\"Black\" size=\"+1\"><b>Clas"
      "sic (RTEID) API</b></font>\n"
      "         </a>\n"
      "      </td>\n"
      "      <td width=\"20\">&nbsp;</td>\n"
      "      <td bgcolor=\"#4040ff\" align=\"center\" wid"
      "th=\"200\">\n"
      "         <a href=\"/goforms/osmonweb?api=POSIX\" n"
      "ame=\"POSIX objects\">\n"
      "         <font color=\"#ffffff\" size=\"+1\">POSIX"
      " API</font>\n"
      "         </a>\n"
      "      </td>\n"
      "      <td width=\"20\">&nbsp;</td>\n"
      "      <td bgcolor=\"#E0E0E0\" align=\"center\" wid"
      "th=\"200\">\n"
      "         <a href=\"/goforms/osmonweb?api=ITRON\" n"
      "ame=\"ITRON objects\">\n"
      "         <font color=\"Black\" size=\"+1\">ITRON A"
      "PI</font>\n"
      "         </a>\n"
      "      </td>\n"
      "      <td width=\"20\">&nbsp;</td>\n"
      "      </tr>\n"
      "      <tr><td colspan=10 bgcolor=\"#4040ff\"><img "
      "width=1 height=1 alt=\"\"></td></tr>\n"
      "   </table>\n"
      "   <!-- end of API selection bar -->\n"
      "\n"
      "   <!-- start of Object selection bar -->\n"
      "   <table border=\"0\"  cellspacing=\"0\" width=\""
      "80%\">\n"
      "      <tr>\n"
      "         <td width=\"20\">&nbsp;</td>\n"
      "         <td bgcolor=\"#8080E0\" align=\"center\" "
      "width=\"200\">\n"
      "            <a href=\"/goforms/osmonweb?api=POSIX&"
      "obj_type=thread\" name=\"POSIX Threads\">\n"
      "            <font color=Black>Threads</font>\n"
      "            </a></td>\n"
      "         <td width=\"20\">&nbsp;</td>\n"
      "         <td bgcolor=\"#8080E0\" align=\"center\" "
      "width=\"200\">\n"
      "            <a href=\"/goforms/osmonweb?api=POSIX&"
      "obj_type=sema\" name=\"POSIX semaphores\">\n"
      "            <font color=\"Black\">Semaphores</font"
      ">\n"
      "            </a></td>\n"
      "         <td width=\"20\">&nbsp;</td>\n"
      "         <td bgcolor=\"#8080E0\" align=\"center\" "
      "width=\"200\">\n"
      "            <a href=\"/goforms/osmonweb?api=POSIX&"
      "obj_type=mutex\" name=\"POSIX Mutexes\">\n"
      "            <font color=\"Black\">Mutexes</font>\n"
      "            </a></td>\n"
      "         <td width=\"20\">&nbsp;</td>\n"
      "         <td bgcolor=\"#8080E0\" align=\"center\" "
      "width=\"200\">\n"
      "            <a href=\"/goforms/osmonweb?api=POSIX&"
      "obj_type=mqueue\" name=\"POSIX Message Queues\">\n"
      "            <font color=\"Black\">Message Queues</"
      "font>\n"
      "            </a></td>\n"
      "         <td width=\"20\">&nbsp;</td>\n"
      "         <td bgcolor=\"#8080E0\" align=\"center\" "
      "width=\"200\">\n"
      "            <a href=\"/goforms/osmonweb?api=POSIX&"
      "obj_type=timer\" name=\"POSIX Timers\">\n"
      "            <font color=\"Black\">Timers</font>\n"
      "            </a></td>\n"
      "         <td width=\"20\">&nbsp;</td>\n"
      "      </tr>\n"
      "   </table>\n"
      "<!-- end of Object selection bar -->\n"
      "   </div>\n"
   ;

   const char osmonweb_POSIX_objs_footer[] =
      "\n"
      "    <br><br><hr><br><br>\n"
      "    <div align=\"center\"><table cellspacing=\"5\""
      " cellpadding=\"15\"><tr>\n"
      "      <td><IMG src=\"/osmonweb/EmpoweredByRTEMSEgg"
      "Logo.gif\" alt=\"Empowered by RTEMS\" width=90 hei"
      "ght=53 border=0></td>\n"
      "      <td><IMG src=\"/osmonweb/@HTTPD_LOGO@\" widt"
      "h=113 height=23 border=0></td>\n"
      "      <td><IMG src=\"/osmonweb/imdlogo.jpg\" width"
      "=123 height=61 border=0></td>\n"
      "    </tr><tr>\n"
      "      <td align=\"center\"><b>Empowered by <br>RTE"
      "MS</b></td>\n"
      "      <td align=\"center\"><b>transported by <br>@"
      "HTTPD_SERVER@</b></td>\n"
      "      <td align=\"center\"><b>implemented by <br>I"
      "MD Th. Dörfler</b></td>\n"
      "    </tr></table></div>\n"
      "    </td></tr>\n"
      "</table>\n"
   ;

   const char osmonweb_POSIX_objs_trailer[] =
      "\n"
      "</body>\n"
   ;

